### ISSUE TITLE
Hazelcast compatibility and continuing contribution

### ISSUE THREAD

**Issue by De1taE1even** [jerrinot/subzero#47]
Hello,

Is there a subzero<->hazelcast version compatibility matrix somewhere that I can look at?  I see the latest release of subzero is 0.10, which is pretty old now, so I don't know if it's compatible with newer versions of Hazelcast.  If not, do you know of an alternative?  I can't find any other kryo<->hazelcast projects.

**Comment by jerrinot** [comment]
hi, I maintain Subzero in my spare time, there are certainly no guarantees. 
That being said I'd like to add support for Hazelcast 5 sooner rather than later and fix some of the issues reported. 

When it comes to alternatives: This depends on your requirements. I'd recommend to have a look at the upcoming [Compact serialization](https://docs.hazelcast.com/hazelcast/5.0/serialization/compact-serialization.html) which is included in Hazelcast 5.0. It's currently in Beta.

**Comment by jerrinot** [comment]
closing in favour of https://github.com/jerrinot/subzero/issues/48

**Comment by De1taE1even** [comment]
Thanks for the reply, I do realize this is a personal effort and appreciate the result.  I only asked because I couldn't find anything that showed me what versions of subzero are compatible with what versions of hazelcast, ie is the current 0.10 version compatible with hazelcast 4.2, etc.
